// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.flex

package scanner;
import static scanner.TokenType.*;
import static scanner.Token.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\2\22\0\1\1"+
    "\1\4\1\5\2\0\1\4\1\6\1\7\2\10\1\11"+
    "\1\12\1\10\1\13\1\10\1\14\1\15\7\16\2\17"+
    "\2\10\1\20\1\21\1\22\1\10\1\0\6\23\21\24"+
    "\1\25\2\24\1\10\1\26\1\10\1\4\1\27\1\0"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\24\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\24\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\10\1\60\2\10\6\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\3\1\1\4\3"+
    "\2\4\1\1\1\3\20\5\1\3\1\0\1\6\4\0"+
    "\1\2\1\4\1\0\6\5\1\7\4\5\1\7\13\5"+
    "\1\10\1\0\1\4\30\5\1\2\27\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\61"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436"+
    "\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\304\0\61\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u02ae\0\u0961\0\u0992\0\u09c3"+
    "\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b"+
    "\0\61\0\u0b7c\0\u0715\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71"+
    "\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9"+
    "\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81"+
    "\0\u0fb2\0\u0fe3\0\u1014\0\61\0\u1045\0\u1076\0\u10a7\0\u10d8"+
    "\0\u1109\0\u113a\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260"+
    "\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u1419\0\u144a\0\u147b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\4\1\11\1\12\1\13\1\14\2\15\1\16\1\4"+
    "\1\17\3\20\2\2\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\20\1\30\1\20\1\31\4\20\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\3\20\1\40\62\0"+
    "\2\3\77\0\1\10\37\0\2\41\1\0\2\41\1\42"+
    "\20\41\1\43\32\41\6\0\1\10\12\0\1\10\37\0"+
    "\2\44\1\0\4\44\1\0\16\44\1\45\32\44\12\0"+
    "\1\10\6\0\1\10\52\0\1\10\5\0\2\10\47\0"+
    "\1\46\2\0\1\47\4\0\1\10\54\0\2\50\6\0"+
    "\1\51\27\0\1\51\20\0\3\15\61\0\1\4\1\10"+
    "\60\0\1\10\1\4\53\0\3\20\3\0\3\20\1\0"+
    "\31\20\16\0\3\20\3\0\3\20\1\0\23\20\1\52"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\20\20\1\53"+
    "\10\20\16\0\3\20\3\0\3\20\1\0\1\20\1\54"+
    "\6\20\1\55\5\20\1\56\12\20\16\0\3\20\3\0"+
    "\3\20\1\0\5\20\1\57\10\20\1\60\12\20\16\0"+
    "\3\20\3\0\3\20\1\0\13\20\1\54\1\20\1\61"+
    "\10\20\1\62\2\20\16\0\3\20\3\0\3\20\1\0"+
    "\13\20\1\63\2\20\1\64\12\20\16\0\3\20\3\0"+
    "\3\20\1\0\16\20\1\52\12\20\16\0\3\20\3\0"+
    "\3\20\1\0\6\20\1\65\6\20\1\66\13\20\16\0"+
    "\3\20\3\0\3\20\1\0\16\20\1\67\12\20\16\0"+
    "\3\20\3\0\3\20\1\0\5\20\1\70\23\20\16\0"+
    "\3\20\3\0\3\20\1\0\10\20\1\71\1\72\10\20"+
    "\1\73\2\20\1\74\3\20\16\0\3\20\3\0\3\20"+
    "\1\0\27\20\1\75\1\20\16\0\3\20\3\0\3\20"+
    "\1\0\15\20\1\76\13\20\16\0\3\20\3\0\3\20"+
    "\1\0\16\20\1\77\12\20\16\0\3\20\3\0\3\20"+
    "\1\0\10\20\1\100\20\20\22\0\1\10\36\0\1\10"+
    "\5\0\1\41\1\0\1\41\16\0\1\41\2\0\1\41"+
    "\3\0\1\41\6\0\1\41\2\0\1\41\1\0\1\41"+
    "\16\0\1\101\56\0\1\44\1\0\1\44\16\0\1\44"+
    "\2\0\1\44\3\0\1\44\6\0\1\44\2\0\1\44"+
    "\1\0\1\44\7\0\11\46\1\102\47\46\2\47\1\0"+
    "\56\47\15\0\2\50\57\0\3\103\3\0\1\103\4\0"+
    "\6\103\40\0\3\20\3\0\3\20\1\0\22\20\1\104"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\5\20\1\105"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\21\20\1\106"+
    "\7\20\16\0\3\20\3\0\3\20\1\0\1\20\1\64"+
    "\27\20\16\0\3\20\3\0\3\20\1\0\15\20\1\107"+
    "\13\20\16\0\3\20\3\0\3\20\1\0\6\20\1\110"+
    "\22\20\16\0\3\20\3\0\3\20\1\0\23\20\1\111"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\23\20\1\112"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\22\20\1\113"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\16\20\1\114"+
    "\12\20\16\0\3\20\3\0\3\20\1\0\20\20\1\65"+
    "\10\20\16\0\3\20\3\0\3\20\1\0\22\20\1\65"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\15\20\1\115"+
    "\13\20\16\0\3\20\3\0\3\20\1\0\7\20\1\116"+
    "\12\20\1\117\6\20\16\0\3\20\3\0\3\20\1\0"+
    "\16\20\1\120\12\20\16\0\3\20\3\0\3\20\1\0"+
    "\7\20\1\121\20\20\1\122\16\0\3\20\3\0\3\20"+
    "\1\0\1\20\1\123\16\20\1\124\10\20\16\0\3\20"+
    "\3\0\3\20\1\0\11\20\1\125\17\20\16\0\3\20"+
    "\3\0\3\20\1\0\17\20\1\126\11\20\16\0\3\20"+
    "\3\0\3\20\1\0\11\20\1\127\7\20\1\130\7\20"+
    "\16\0\3\20\3\0\3\20\1\0\11\20\1\131\1\20"+
    "\1\132\15\20\16\0\3\20\3\0\3\20\1\0\11\20"+
    "\1\133\17\20\1\0\11\46\1\102\2\46\1\134\44\46"+
    "\15\0\3\20\3\0\3\20\1\0\16\20\1\65\12\20"+
    "\16\0\3\20\3\0\3\20\1\0\1\20\1\135\27\20"+
    "\16\0\3\20\3\0\3\20\1\0\5\20\1\65\23\20"+
    "\16\0\3\20\3\0\3\20\1\0\21\20\1\66\1\136"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\1\20\1\137"+
    "\27\20\16\0\3\20\3\0\3\20\1\0\2\20\1\133"+
    "\26\20\16\0\3\20\3\0\3\20\1\0\14\20\1\65"+
    "\14\20\16\0\3\20\3\0\3\20\1\0\5\20\1\140"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\1\20\1\66"+
    "\27\20\16\0\3\20\3\0\3\20\1\0\7\20\1\65"+
    "\21\20\16\0\3\20\3\0\3\20\1\0\11\20\1\141"+
    "\17\20\16\0\3\20\3\0\3\20\1\0\23\20\1\140"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\20\20\1\66"+
    "\10\20\16\0\3\20\3\0\3\20\1\0\15\20\1\142"+
    "\13\20\16\0\3\20\3\0\3\20\1\0\5\20\1\143"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\22\20\1\144"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\23\20\1\145"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\22\20\1\146"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\5\20\1\147"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\16\20\1\150"+
    "\12\20\16\0\3\20\3\0\3\20\1\0\11\20\1\151"+
    "\17\20\16\0\3\20\3\0\3\20\1\0\4\20\1\65"+
    "\24\20\16\0\3\20\3\0\3\20\1\0\1\20\1\152"+
    "\27\20\16\0\3\20\3\0\3\20\1\0\13\20\1\106"+
    "\15\20\16\0\3\20\3\0\3\20\1\0\12\20\1\65"+
    "\16\20\16\0\3\20\3\0\3\20\1\0\11\20\1\153"+
    "\17\20\16\0\3\20\3\0\3\20\1\0\23\20\1\154"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\20\20\1\150"+
    "\10\20\16\0\3\20\3\0\3\20\1\0\21\20\1\155"+
    "\7\20\16\0\3\20\3\0\3\20\1\0\5\20\1\131"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\16\20\1\156"+
    "\12\20\16\0\3\20\3\0\3\20\1\0\11\20\1\157"+
    "\17\20\16\0\3\20\3\0\3\20\1\0\3\20\1\66"+
    "\25\20\16\0\3\20\3\0\3\20\1\0\3\20\1\160"+
    "\25\20\16\0\3\20\3\0\3\20\1\0\4\20\1\161"+
    "\24\20\16\0\3\20\3\0\3\20\1\0\15\20\1\65"+
    "\13\20\16\0\3\20\3\0\3\20\1\0\7\20\1\121"+
    "\21\20\16\0\3\20\3\0\3\20\1\0\22\20\1\100"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\15\20\1\162"+
    "\13\20\16\0\3\20\3\0\3\20\1\0\13\20\1\66"+
    "\15\20\16\0\3\20\3\0\3\20\1\0\22\20\1\163"+
    "\6\20\16\0\3\20\3\0\3\20\1\0\6\20\1\65"+
    "\22\20\16\0\3\20\3\0\3\20\1\0\3\20\1\65"+
    "\25\20\16\0\3\20\3\0\3\20\1\0\10\20\1\65"+
    "\20\20\16\0\3\20\3\0\3\20\1\0\5\20\1\156"+
    "\23\20\16\0\3\20\3\0\3\20\1\0\23\20\1\106"+
    "\5\20\16\0\3\20\3\0\3\20\1\0\5\20\1\64"+
    "\23\20\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5292];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\30\1\1\0\1\11\4\0"+
    "\2\1\1\0\27\1\1\11\1\0\31\1\1\11\27\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(TokenType type, Object value){
        return new Token(type, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(ERROR, yytext());
            }
            // fall through
          case 9: break;
          case 2:
            { /*Ignore*/
            }
            // fall through
          case 10: break;
          case 3:
            { return token(OPERATOR, yytext());
            }
            // fall through
          case 11: break;
          case 4:
            { return token(INTEGER, yytext());
            }
            // fall through
          case 12: break;
          case 5:
            { return token(IDENTIFIER, yytext());
            }
            // fall through
          case 13: break;
          case 6:
            { return token(STRING, yytext());
            }
            // fall through
          case 14: break;
          case 7:
            { return token(KEYWORD, yytext());
            }
            // fall through
          case 15: break;
          case 8:
            { return token(CHAR, yytext());
            }
            // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
