// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.flex

package model.compiler.scanner;
import static model.compiler.scanner.TokenType.*;
import static model.compiler.scanner.Token.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\2\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\10\2\11\1\12"+
    "\1\13\1\11\1\14\1\15\1\16\1\17\7\20\2\21"+
    "\2\11\1\22\1\23\1\24\1\11\1\0\4\25\1\26"+
    "\1\25\21\27\1\30\2\27\1\11\1\31\1\11\1\4"+
    "\1\32\1\0\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\27\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\27\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\11\1\63\1\11\1\64"+
    "\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\3\1\1"+
    "\1\5\2\4\1\5\1\4\2\6\1\3\1\5\1\3"+
    "\21\7\2\3\1\0\1\10\1\0\1\4\2\0\1\11"+
    "\1\0\1\2\1\6\4\0\6\7\1\12\4\7\1\12"+
    "\13\7\1\13\1\0\1\11\1\6\30\7\1\2\27\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\65\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\237\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459"+
    "\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601"+
    "\0\u0636\0\u066b\0\u06a0\0\u06d5\0\65\0\324\0\65\0\u070a"+
    "\0\65\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d"+
    "\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25"+
    "\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0350\0\u0b98"+
    "\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40"+
    "\0\u0d75\0\u0daa\0\65\0\u0ddf\0\u091c\0\u08e7\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1"+
    "\0\u1026\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199"+
    "\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\65\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\6\1\12\1\13\1\14\1\15\1\16\2\17"+
    "\1\20\1\21\1\22\1\23\1\24\2\23\2\2\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\23\1\34"+
    "\1\23\1\35\4\23\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\3\23\1\44\1\45\66\0\2\3\105\0\1\45"+
    "\41\0\2\46\1\0\2\46\1\47\23\46\1\50\33\46"+
    "\23\0\1\51\50\0\1\45\13\0\1\45\41\0\2\52"+
    "\1\0\5\52\1\0\20\52\1\53\33\52\13\0\1\51"+
    "\7\0\1\51\55\0\1\51\6\0\1\51\1\11\57\0"+
    "\3\54\55\0\1\55\3\0\1\56\4\0\1\51\56\0"+
    "\1\54\1\0\2\57\1\60\4\0\1\61\1\0\1\62"+
    "\6\0\1\61\20\0\1\62\21\0\1\54\1\0\3\17"+
    "\4\0\1\61\10\0\1\61\47\0\1\4\1\45\64\0"+
    "\1\45\1\4\57\0\3\23\3\0\4\23\1\0\31\23"+
    "\15\0\2\63\2\0\3\23\3\0\4\23\1\0\31\23"+
    "\21\0\3\23\3\0\4\23\1\0\23\23\1\64\5\23"+
    "\21\0\3\23\3\0\4\23\1\0\20\23\1\65\10\23"+
    "\21\0\3\23\3\0\4\23\1\0\1\23\1\66\6\23"+
    "\1\67\5\23\1\70\12\23\21\0\3\23\3\0\4\23"+
    "\1\0\5\23\1\71\10\23\1\72\12\23\15\0\2\63"+
    "\2\0\3\23\3\0\4\23\1\0\13\23\1\66\1\23"+
    "\1\73\10\23\1\74\2\23\21\0\3\23\3\0\4\23"+
    "\1\0\13\23\1\75\2\23\1\76\12\23\21\0\3\23"+
    "\3\0\4\23\1\0\16\23\1\64\12\23\21\0\3\23"+
    "\3\0\4\23\1\0\6\23\1\77\6\23\1\100\13\23"+
    "\21\0\3\23\3\0\4\23\1\0\16\23\1\101\12\23"+
    "\21\0\3\23\3\0\4\23\1\0\5\23\1\102\23\23"+
    "\21\0\3\23\3\0\4\23\1\0\10\23\1\103\1\104"+
    "\10\23\1\105\2\23\1\106\3\23\21\0\3\23\3\0"+
    "\4\23\1\0\27\23\1\107\1\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\110\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\16\23\1\111\12\23\21\0\3\23\3\0"+
    "\4\23\1\0\10\23\1\112\20\23\25\0\1\45\37\0"+
    "\1\45\6\0\1\46\2\0\1\46\20\0\1\46\2\0"+
    "\1\46\3\0\1\46\6\0\1\46\2\0\1\46\1\0"+
    "\1\46\20\0\1\113\61\0\1\52\2\0\1\52\20\0"+
    "\1\52\2\0\1\52\3\0\1\52\6\0\1\52\2\0"+
    "\1\52\1\0\1\52\27\0\3\54\4\0\1\61\10\0"+
    "\1\61\25\0\12\55\1\114\52\55\2\56\1\0\62\56"+
    "\15\0\1\54\1\0\2\57\1\60\4\0\1\61\10\0"+
    "\1\61\42\0\1\54\1\0\3\60\4\0\1\61\10\0"+
    "\1\61\40\0\2\63\2\0\3\115\62\0\3\116\3\0"+
    "\2\116\4\0\6\116\43\0\3\115\62\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\117\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\120\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\21\23\1\121\7\23\21\0\3\23\3\0"+
    "\4\23\1\0\1\23\1\76\27\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\122\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\6\23\1\123\22\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\124\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\125\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\126\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\16\23\1\127\12\23\21\0\3\23\3\0"+
    "\4\23\1\0\20\23\1\77\10\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\77\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\130\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\7\23\1\131\12\23\1\132\6\23\21\0"+
    "\3\23\3\0\4\23\1\0\16\23\1\133\12\23\21\0"+
    "\3\23\3\0\4\23\1\0\7\23\1\134\20\23\1\135"+
    "\21\0\3\23\3\0\4\23\1\0\1\23\1\136\16\23"+
    "\1\137\10\23\21\0\3\23\3\0\4\23\1\0\11\23"+
    "\1\140\17\23\21\0\3\23\3\0\4\23\1\0\17\23"+
    "\1\141\11\23\21\0\3\23\3\0\4\23\1\0\11\23"+
    "\1\142\7\23\1\143\7\23\21\0\3\23\3\0\4\23"+
    "\1\0\11\23\1\144\1\23\1\145\15\23\21\0\3\23"+
    "\3\0\4\23\1\0\11\23\1\146\17\23\2\0\12\55"+
    "\1\114\3\55\1\147\46\55\17\0\3\23\3\0\4\23"+
    "\1\0\16\23\1\77\12\23\21\0\3\23\3\0\4\23"+
    "\1\0\1\23\1\150\27\23\21\0\3\23\3\0\4\23"+
    "\1\0\5\23\1\77\23\23\21\0\3\23\3\0\4\23"+
    "\1\0\21\23\1\100\1\151\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\1\23\1\152\27\23\21\0\3\23\3\0"+
    "\4\23\1\0\2\23\1\146\26\23\21\0\3\23\3\0"+
    "\4\23\1\0\14\23\1\77\14\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\153\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\1\23\1\100\27\23\21\0\3\23\3\0"+
    "\4\23\1\0\7\23\1\77\21\23\21\0\3\23\3\0"+
    "\4\23\1\0\11\23\1\154\17\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\153\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\20\23\1\100\10\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\155\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\156\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\157\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\160\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\161\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\162\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\16\23\1\163\12\23\21\0\3\23\3\0"+
    "\4\23\1\0\11\23\1\164\17\23\21\0\3\23\3\0"+
    "\4\23\1\0\4\23\1\77\24\23\21\0\3\23\3\0"+
    "\4\23\1\0\1\23\1\165\27\23\21\0\3\23\3\0"+
    "\4\23\1\0\13\23\1\121\15\23\21\0\3\23\3\0"+
    "\4\23\1\0\12\23\1\77\16\23\21\0\3\23\3\0"+
    "\4\23\1\0\11\23\1\166\17\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\167\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\20\23\1\163\10\23\21\0\3\23\3\0"+
    "\4\23\1\0\21\23\1\170\7\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\144\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\16\23\1\171\12\23\21\0\3\23\3\0"+
    "\4\23\1\0\11\23\1\172\17\23\21\0\3\23\3\0"+
    "\4\23\1\0\3\23\1\100\25\23\21\0\3\23\3\0"+
    "\4\23\1\0\3\23\1\173\25\23\21\0\3\23\3\0"+
    "\4\23\1\0\4\23\1\174\24\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\77\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\7\23\1\134\21\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\112\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\15\23\1\175\13\23\21\0\3\23\3\0"+
    "\4\23\1\0\13\23\1\100\15\23\21\0\3\23\3\0"+
    "\4\23\1\0\22\23\1\176\6\23\21\0\3\23\3\0"+
    "\4\23\1\0\6\23\1\77\22\23\21\0\3\23\3\0"+
    "\4\23\1\0\3\23\1\77\25\23\21\0\3\23\3\0"+
    "\4\23\1\0\10\23\1\77\20\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\171\23\23\21\0\3\23\3\0"+
    "\4\23\1\0\23\23\1\121\5\23\21\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\76\23\23\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6095];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\33\1\1\11\1\0\1\11"+
    "\1\0\1\11\2\0\1\1\1\0\2\1\4\0\27\1"+
    "\1\11\1\0\32\1\1\11\27\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(TokenType type, Object value){
        return new Token(type, value, yyline);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(ERROR, yytext());
            }
            // fall through
          case 12: break;
          case 2:
            { /*Ignore*/
            }
            // fall through
          case 13: break;
          case 3:
            { return token(OP_LOGICAL, yytext());
            }
            // fall through
          case 14: break;
          case 4:
            { return token(OP_ARITHMETIC, yytext());
            }
            // fall through
          case 15: break;
          case 5:
            { return token(OP_STRUCTURE, yytext());
            }
            // fall through
          case 16: break;
          case 6:
            { return token(INTEGER, yytext());
            }
            // fall through
          case 17: break;
          case 7:
            { return token(IDENTIFIER, yytext());
            }
            // fall through
          case 18: break;
          case 8:
            { return token(STRING, yytext());
            }
            // fall through
          case 19: break;
          case 9:
            { return token(FLOAT, yytext());
            }
            // fall through
          case 20: break;
          case 10:
            { return token(KEYWORD, yytext());
            }
            // fall through
          case 21: break;
          case 11:
            { return token(CHAR, yytext());
            }
            // fall through
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
