// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.flex

package model.compiler.scanner;
import model.compiler.parser.sym;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\2\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\3\22"+
    "\4\23\2\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\0\4\33\1\34\1\33\21\35\1\36\2\35\1\37"+
    "\1\40\1\41\1\42\1\43\1\0\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\35\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\35\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\1\73\1\74"+
    "\1\75\1\76\1\77\6\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\1\17\25\1\31\1\32\1\33"+
    "\1\34\1\35\1\0\1\36\1\0\1\37\1\40\1\41"+
    "\2\0\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\0\1\2\1\51\1\16\1\0\2\1\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\6\25\1\60\6\25\1\61"+
    "\14\25\1\62\1\63\1\64\5\0\1\50\1\16\1\65"+
    "\1\66\13\25\1\67\1\25\1\70\21\25\1\50\1\2"+
    "\1\71\1\25\1\72\1\73\4\25\1\74\1\75\2\25"+
    "\1\76\1\77\1\100\13\25\1\101\3\25\1\102\1\103"+
    "\4\25\1\104\2\25\1\105\6\25\1\106\2\25\1\107"+
    "\1\110\2\25\1\111\1\112\1\25\1\113\1\114\1\115"+
    "\1\116\1\117\1\120\4\25\1\121\1\25\1\122\2\25"+
    "\1\123\1\124\1\125\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\u0180\0\u01c0"+
    "\0\100\0\100\0\u0200\0\u0240\0\100\0\u0280\0\u02c0\0\u0300"+
    "\0\u0340\0\u0380\0\100\0\100\0\u03c0\0\u0400\0\u0440\0\100"+
    "\0\u0480\0\100\0\100\0\u04c0\0\u0500\0\u0540\0\u0580\0\u05c0"+
    "\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\u0780\0\u07c0"+
    "\0\u0800\0\u0840\0\u0880\0\u08c0\0\100\0\u0900\0\100\0\100"+
    "\0\100\0\u0100\0\100\0\u0940\0\100\0\100\0\100\0\u0980"+
    "\0\u09c0\0\100\0\100\0\100\0\100\0\100\0\100\0\u0a00"+
    "\0\u0a40\0\u0a80\0\100\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0"+
    "\0\100\0\100\0\100\0\u0c00\0\100\0\u0c40\0\u0c80\0\u0cc0"+
    "\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0f00\0\u0f40\0\u0480\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080"+
    "\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\100"+
    "\0\100\0\100\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0"+
    "\0\u0b80\0\100\0\100\0\u1400\0\u1440\0\u1480\0\u14c0\0\u1500"+
    "\0\u1540\0\u1580\0\u15c0\0\u1600\0\u1640\0\u1680\0\u0480\0\u16c0"+
    "\0\u0480\0\u1700\0\u1740\0\u1780\0\u17c0\0\u1800\0\u1840\0\u1880"+
    "\0\u18c0\0\u1900\0\u1940\0\u1980\0\u19c0\0\u1a00\0\u1a40\0\u1a80"+
    "\0\u1ac0\0\u1b00\0\u1380\0\100\0\u0480\0\u1b40\0\u0480\0\u0480"+
    "\0\u1b80\0\u1bc0\0\u1c00\0\u1c40\0\u0480\0\u0480\0\u1c80\0\u1cc0"+
    "\0\u0480\0\u0480\0\u0480\0\u1d00\0\u1d40\0\u1d80\0\u1dc0\0\u1e00"+
    "\0\u1e40\0\u1e80\0\u1ec0\0\u1f00\0\u1f40\0\u1f80\0\u0480\0\u1fc0"+
    "\0\u2000\0\u2040\0\u0480\0\u0480\0\u2080\0\u20c0\0\u2100\0\u2140"+
    "\0\u0480\0\u2180\0\u21c0\0\u0480\0\u2200\0\u2240\0\u2280\0\u22c0"+
    "\0\u2300\0\u2340\0\u0480\0\u2380\0\u23c0\0\u0480\0\u0480\0\u2400"+
    "\0\u2440\0\u0480\0\u0480\0\u2480\0\u0480\0\u0480\0\u0480\0\u0480"+
    "\0\u0480\0\u0480\0\u24c0\0\u2500\0\u2540\0\u2580\0\u0480\0\u25c0"+
    "\0\u0480\0\u2600\0\u2640\0\u0480\0\u0480\0\u0480\0\u0480";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\3\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\4\31\1\32\1\2\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\31\1\45\1\31"+
    "\1\46\4\31\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\3\31\1\55\1\56\1\57\1\60\101\0\2\3\125\0"+
    "\1\61\47\0\2\62\1\0\2\62\1\63\32\62\1\64"+
    "\37\62\30\0\1\65\56\0\1\66\20\0\1\67\47\0"+
    "\2\70\1\0\5\70\1\0\27\70\1\71\37\70\30\0"+
    "\1\72\63\0\1\73\13\0\1\74\65\0\1\75\11\0"+
    "\1\76\1\77\67\0\4\100\66\0\1\101\4\0\1\102"+
    "\7\0\1\103\66\0\1\100\1\0\3\104\1\105\6\0"+
    "\1\35\1\106\1\35\1\107\4\0\5\35\1\106\20\35"+
    "\1\107\2\35\23\0\1\100\1\0\4\22\6\0\1\35"+
    "\1\106\2\35\4\0\5\35\1\106\23\35\33\0\1\110"+
    "\1\111\77\0\1\112\77\0\1\113\1\114\67\0\4\31"+
    "\6\0\4\31\4\0\31\31\34\0\1\115\70\0\4\35"+
    "\6\0\4\35\4\0\31\35\25\0\4\31\6\0\4\31"+
    "\4\0\23\31\1\116\5\31\25\0\4\31\6\0\4\31"+
    "\4\0\20\31\1\117\10\31\25\0\4\31\6\0\4\31"+
    "\4\0\1\31\1\120\6\31\1\121\5\31\1\122\12\31"+
    "\25\0\4\31\6\0\4\31\4\0\5\31\1\123\10\31"+
    "\1\124\12\31\25\0\4\31\6\0\4\31\4\0\13\31"+
    "\1\125\1\31\1\126\10\31\1\127\2\31\25\0\4\31"+
    "\6\0\4\31\4\0\13\31\1\130\2\31\1\131\12\31"+
    "\25\0\4\31\6\0\4\31\4\0\16\31\1\132\12\31"+
    "\25\0\4\31\6\0\4\31\4\0\6\31\1\133\6\31"+
    "\1\134\13\31\25\0\4\31\6\0\4\31\4\0\16\31"+
    "\1\135\12\31\25\0\4\31\6\0\4\31\4\0\5\31"+
    "\1\136\23\31\25\0\4\31\6\0\4\31\4\0\10\31"+
    "\1\137\1\140\10\31\1\141\2\31\1\142\3\31\25\0"+
    "\4\31\6\0\4\31\4\0\27\31\1\143\1\31\25\0"+
    "\4\31\6\0\4\31\4\0\15\31\1\144\13\31\25\0"+
    "\4\31\6\0\4\31\4\0\16\31\1\145\12\31\25\0"+
    "\4\31\6\0\4\31\4\0\10\31\1\146\7\31\1\147"+
    "\10\31\34\0\1\150\44\0\1\151\7\0\1\62\2\0"+
    "\1\62\10\0\3\62\14\0\1\62\4\0\1\62\3\0"+
    "\1\62\6\0\1\62\2\0\1\62\1\0\1\62\22\0"+
    "\1\152\74\0\1\70\2\0\1\70\10\0\2\153\1\154"+
    "\14\0\1\70\4\0\1\70\3\0\1\70\6\0\1\70"+
    "\2\0\1\70\1\0\1\70\33\0\4\100\7\0\1\155"+
    "\13\0\1\155\27\0\13\101\1\156\64\101\2\102\1\0"+
    "\75\102\17\0\1\100\1\0\3\104\1\105\6\0\1\35"+
    "\1\106\2\35\4\0\5\35\1\106\23\35\23\0\1\100"+
    "\1\0\4\105\6\0\1\35\1\106\2\35\4\0\5\35"+
    "\1\106\23\35\20\0\1\157\1\0\1\157\2\0\4\160"+
    "\6\0\4\35\4\0\31\35\25\0\4\161\6\0\2\161"+
    "\2\35\4\0\1\35\6\161\22\35\34\0\1\162\77\0"+
    "\1\163\70\0\4\31\6\0\4\31\4\0\22\31\1\164"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\5\31\1\165"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\21\31\1\166"+
    "\7\31\25\0\4\31\6\0\4\31\4\0\1\31\1\167"+
    "\27\31\25\0\4\31\6\0\4\31\4\0\15\31\1\170"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\6\31\1\171"+
    "\22\31\25\0\4\31\6\0\4\31\4\0\23\31\1\172"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\21\31\1\173"+
    "\7\31\25\0\4\31\6\0\4\31\4\0\23\31\1\174"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\22\31\1\175"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\16\31\1\176"+
    "\12\31\25\0\4\31\6\0\4\31\4\0\20\31\1\177"+
    "\10\31\25\0\4\31\6\0\4\31\4\0\22\31\1\200"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\22\31\1\201"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\15\31\1\202"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\1\31\1\203"+
    "\5\31\1\204\12\31\1\205\6\31\25\0\4\31\6\0"+
    "\4\31\4\0\16\31\1\206\12\31\25\0\4\31\6\0"+
    "\4\31\4\0\7\31\1\207\20\31\1\210\25\0\4\31"+
    "\6\0\4\31\4\0\1\31\1\211\16\31\1\212\10\31"+
    "\25\0\4\31\6\0\4\31\4\0\11\31\1\213\17\31"+
    "\25\0\4\31\6\0\4\31\4\0\17\31\1\214\11\31"+
    "\25\0\4\31\6\0\4\31\4\0\11\31\1\215\7\31"+
    "\1\216\7\31\25\0\4\31\6\0\4\31\4\0\11\31"+
    "\1\217\1\31\1\220\15\31\25\0\4\31\6\0\4\31"+
    "\4\0\11\31\1\221\17\31\25\0\4\31\6\0\4\31"+
    "\4\0\11\31\1\222\17\31\14\0\1\152\10\0\3\154"+
    "\64\0\1\152\10\0\3\70\70\0\1\157\1\0\1\157"+
    "\2\0\4\223\53\0\13\101\1\156\4\101\1\224\57\101"+
    "\21\0\4\223\74\0\4\160\6\0\4\35\4\0\31\35"+
    "\25\0\4\31\6\0\4\31\4\0\16\31\1\225\12\31"+
    "\25\0\4\31\6\0\4\31\4\0\1\31\1\226\27\31"+
    "\25\0\4\31\6\0\4\31\4\0\5\31\1\227\23\31"+
    "\25\0\4\31\6\0\4\31\4\0\20\31\1\230\10\31"+
    "\25\0\4\31\6\0\4\31\4\0\21\31\1\231\1\232"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\1\31\1\233"+
    "\27\31\25\0\4\31\6\0\4\31\4\0\2\31\1\234"+
    "\26\31\25\0\4\31\6\0\4\31\4\0\5\31\1\235"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\14\31\1\236"+
    "\14\31\25\0\4\31\6\0\4\31\4\0\5\31\1\237"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\1\31\1\240"+
    "\27\31\25\0\4\31\6\0\4\31\4\0\16\31\1\241"+
    "\12\31\25\0\4\31\6\0\4\31\4\0\7\31\1\242"+
    "\21\31\25\0\4\31\6\0\4\31\4\0\4\31\1\243"+
    "\24\31\25\0\4\31\6\0\4\31\4\0\11\31\1\244"+
    "\17\31\25\0\4\31\6\0\4\31\4\0\23\31\1\245"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\20\31\1\246"+
    "\10\31\25\0\4\31\6\0\4\31\4\0\15\31\1\247"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\5\31\1\250"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\22\31\1\251"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\23\31\1\252"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\22\31\1\253"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\5\31\1\254"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\16\31\1\255"+
    "\12\31\25\0\4\31\6\0\4\31\4\0\11\31\1\256"+
    "\17\31\25\0\4\31\6\0\4\31\4\0\4\31\1\257"+
    "\24\31\25\0\4\31\6\0\4\31\4\0\1\31\1\260"+
    "\27\31\25\0\4\31\6\0\4\31\4\0\13\31\1\261"+
    "\15\31\25\0\4\31\6\0\4\31\4\0\22\31\1\262"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\12\31\1\263"+
    "\16\31\25\0\4\31\6\0\4\31\4\0\22\31\1\264"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\11\31\1\265"+
    "\17\31\25\0\4\31\6\0\4\31\4\0\23\31\1\266"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\13\31\1\267"+
    "\15\31\25\0\4\31\6\0\4\31\4\0\20\31\1\270"+
    "\10\31\25\0\4\31\6\0\4\31\4\0\22\31\1\271"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\21\31\1\272"+
    "\7\31\25\0\4\31\6\0\4\31\4\0\20\31\1\273"+
    "\10\31\25\0\4\31\6\0\4\31\4\0\22\31\1\274"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\5\31\1\275"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\16\31\1\276"+
    "\12\31\25\0\4\31\6\0\4\31\4\0\11\31\1\277"+
    "\17\31\25\0\4\31\6\0\4\31\4\0\3\31\1\300"+
    "\25\31\25\0\4\31\6\0\4\31\4\0\3\31\1\301"+
    "\25\31\25\0\4\31\6\0\4\31\4\0\4\31\1\302"+
    "\24\31\25\0\4\31\6\0\4\31\4\0\15\31\1\303"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\7\31\1\304"+
    "\21\31\25\0\4\31\6\0\4\31\4\0\22\31\1\305"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\5\31\1\306"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\5\31\1\307"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\15\31\1\310"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\13\31\1\311"+
    "\15\31\25\0\4\31\6\0\4\31\4\0\5\31\1\312"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\15\31\1\313"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\22\31\1\314"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\15\31\1\315"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\4\31\1\316"+
    "\24\31\25\0\4\31\6\0\4\31\4\0\6\31\1\317"+
    "\22\31\25\0\4\31\6\0\4\31\4\0\3\31\1\320"+
    "\25\31\25\0\4\31\6\0\4\31\4\0\22\31\1\321"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\10\31\1\322"+
    "\20\31\25\0\4\31\6\0\4\31\4\0\5\31\1\323"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\15\31\1\324"+
    "\13\31\25\0\4\31\6\0\4\31\4\0\11\31\1\325"+
    "\17\31\25\0\4\31\6\0\4\31\4\0\23\31\1\326"+
    "\5\31\25\0\4\31\6\0\4\31\4\0\22\31\1\327"+
    "\6\31\25\0\4\31\6\0\4\31\4\0\5\31\1\330"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\6\31\1\331"+
    "\22\31\25\0\4\31\6\0\4\31\4\0\5\31\1\332"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\13\31\1\333"+
    "\15\31\25\0\4\31\6\0\4\31\4\0\5\31\1\334"+
    "\23\31\25\0\4\31\6\0\4\31\4\0\20\31\1\335"+
    "\10\31\25\0\4\31\6\0\4\31\4\0\4\31\1\336"+
    "\24\31\25\0\4\31\6\0\4\31\4\0\5\31\1\337"+
    "\23\31\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9856];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\2\11\2\1\1\11\5\1\2\11"+
    "\3\1\1\11\1\1\2\11\21\1\1\11\1\1\3\11"+
    "\1\0\1\11\1\0\3\11\2\0\6\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\3\1\3\11\1\1\1\11"+
    "\32\1\3\11\5\0\2\1\2\11\40\1\1\11\113\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yycolumn, yyline, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.LEX_ERROR, yytext());
            }
            // fall through
          case 87: break;
          case 2:
            { /*Ignore*/
            }
            // fall through
          case 88: break;
          case 3:
            { return symbol(sym.OP_NOT, yytext());
            }
            // fall through
          case 89: break;
          case 4:
            { return symbol(sym.OP_MOD, yytext());
            }
            // fall through
          case 90: break;
          case 5:
            { return symbol(sym.OP_BITAND, yytext());
            }
            // fall through
          case 91: break;
          case 6:
            { return symbol(sym.OP_PAR_OPEN, yytext());
            }
            // fall through
          case 92: break;
          case 7:
            { return symbol(sym.OP_PAR_CLOSE, yytext());
            }
            // fall through
          case 93: break;
          case 8:
            { return symbol(sym.OP_MULT, yytext());
            }
            // fall through
          case 94: break;
          case 9:
            { return symbol(sym.OP_ADD, yytext());
            }
            // fall through
          case 95: break;
          case 10:
            { return symbol(sym.OP_COMA, yytext());
            }
            // fall through
          case 96: break;
          case 11:
            { return symbol(sym.OP_SUB, yytext());
            }
            // fall through
          case 97: break;
          case 12:
            { return symbol(sym.OP_DOT, yytext());
            }
            // fall through
          case 98: break;
          case 13:
            { return symbol(sym.OP_DIV, yytext());
            }
            // fall through
          case 99: break;
          case 14:
            { return symbol(sym.INT, yytext());
            }
            // fall through
          case 100: break;
          case 15:
            { return symbol(sym.OP_COLON, yytext());
            }
            // fall through
          case 101: break;
          case 16:
            { return symbol(sym.OP_SEMICOL, yytext());
            }
            // fall through
          case 102: break;
          case 17:
            { return symbol(sym.OP_LESS, yytext());
            }
            // fall through
          case 103: break;
          case 18:
            { return symbol(sym.OP_ASSIGN, yytext());
            }
            // fall through
          case 104: break;
          case 19:
            { return symbol(sym.OP_GREATER, yytext());
            }
            // fall through
          case 105: break;
          case 20:
            { return symbol(sym.OP_QUEST, yytext());
            }
            // fall through
          case 106: break;
          case 21:
            { return symbol(sym.ID, yytext());
            }
            // fall through
          case 107: break;
          case 22:
            { return symbol(sym.OP_BRACK_OPEN, yytext());
            }
            // fall through
          case 108: break;
          case 23:
            { return symbol(sym.OP_BRACK_CLOSE, yytext());
            }
            // fall through
          case 109: break;
          case 24:
            { return symbol(sym.OP_BITOREXC, yytext());
            }
            // fall through
          case 110: break;
          case 25:
            { return symbol(sym.OP_BRACE_OPEN, yytext());
            }
            // fall through
          case 111: break;
          case 26:
            { return symbol(sym.OP_BITOR, yytext());
            }
            // fall through
          case 112: break;
          case 27:
            { return symbol(sym.OP_BRACE_CLOSE, yytext());
            }
            // fall through
          case 113: break;
          case 28:
            { return symbol(sym.OP_BITCOMPL, yytext());
            }
            // fall through
          case 114: break;
          case 29:
            { return symbol(sym.OP_NOT_EQ, yytext());
            }
            // fall through
          case 115: break;
          case 30:
            { return symbol(sym.STRING, yytext());
            }
            // fall through
          case 116: break;
          case 31:
            { return symbol(sym.OP_MOD_ASS, yytext());
            }
            // fall through
          case 117: break;
          case 32:
            { return symbol(sym.OP_AND, yytext());
            }
            // fall through
          case 118: break;
          case 33:
            { return symbol(sym.OP_BITAND_ASS, yytext());
            }
            // fall through
          case 119: break;
          case 34:
            { return symbol(sym.OP_MULT_ASS, yytext());
            }
            // fall through
          case 120: break;
          case 35:
            { return symbol(sym.OP_INC, yytext());
            }
            // fall through
          case 121: break;
          case 36:
            { return symbol(sym.OP_ADD_ASS, yytext());
            }
            // fall through
          case 122: break;
          case 37:
            { return symbol(sym.OP_DEC, yytext());
            }
            // fall through
          case 123: break;
          case 38:
            { return symbol(sym.OP_SUB_ASS, yytext());
            }
            // fall through
          case 124: break;
          case 39:
            { return symbol(sym.OP_ARROW, yytext());
            }
            // fall through
          case 125: break;
          case 40:
            { return symbol(sym.FLOAT, yytext());
            }
            // fall through
          case 126: break;
          case 41:
            { return symbol(sym.OP_DIV_ASS, yytext());
            }
            // fall through
          case 127: break;
          case 42:
            { return symbol(sym.OP_LSHIFT, yytext());
            }
            // fall through
          case 128: break;
          case 43:
            { return symbol(sym.OP_LESS_EQ, yytext());
            }
            // fall through
          case 129: break;
          case 44:
            { return symbol(sym.OP_EQUAL, yytext());
            }
            // fall through
          case 130: break;
          case 45:
            { return symbol(sym.OP_GRE_EQ, yytext());
            }
            // fall through
          case 131: break;
          case 46:
            { return symbol(sym.OP_RSHIFT, yytext());
            }
            // fall through
          case 132: break;
          case 47:
            { return symbol(sym.OP_BITOREXC_ASS, yytext());
            }
            // fall through
          case 133: break;
          case 48:
            { return symbol(sym.KEY_DO, yytext());
            }
            // fall through
          case 134: break;
          case 49:
            { return symbol(sym.KEY_IF, yytext());
            }
            // fall through
          case 135: break;
          case 50:
            { return symbol(sym.OP_BITOR_ASS, yytext());
            }
            // fall through
          case 136: break;
          case 51:
            { return symbol(sym.OP_OR, yytext());
            }
            // fall through
          case 137: break;
          case 52:
            { return symbol(sym.CHAR, yytext());
            }
            // fall through
          case 138: break;
          case 53:
            { return symbol(sym.OP_RSHIFT_ASS, yytext());
            }
            // fall through
          case 139: break;
          case 54:
            { return symbol(sym.OP_LSHIFT_ASS, yytext());
            }
            // fall through
          case 140: break;
          case 55:
            { return symbol(sym.KEY_FOR, yytext());
            }
            // fall through
          case 141: break;
          case 56:
            { return symbol(sym.KEY_INT, yytext());
            }
            // fall through
          case 142: break;
          case 57:
            { return symbol(sym.KEY_AUTO, yytext());
            }
            // fall through
          case 143: break;
          case 58:
            { return symbol(sym.KEY_CASE, yytext());
            }
            // fall through
          case 144: break;
          case 59:
            { return symbol(sym.KEY_CHAR, yytext());
            }
            // fall through
          case 145: break;
          case 60:
            { return symbol(sym.KEY_ELSE, yytext());
            }
            // fall through
          case 146: break;
          case 61:
            { return symbol(sym.KEY_ENUM, yytext());
            }
            // fall through
          case 147: break;
          case 62:
            { return symbol(sym.KEY_GOTO, yytext());
            }
            // fall through
          case 148: break;
          case 63:
            { return symbol(sym.KEY_LONG, yytext());
            }
            // fall through
          case 149: break;
          case 64:
            { return symbol(sym.KEY_READ, yytext());
            }
            // fall through
          case 150: break;
          case 65:
            { return symbol(sym.KEY_VOID, yytext());
            }
            // fall through
          case 151: break;
          case 66:
            { return symbol(sym.KEY_BREAK, yytext());
            }
            // fall through
          case 152: break;
          case 67:
            { return symbol(sym.KEY_CONST, yytext());
            }
            // fall through
          case 153: break;
          case 68:
            { return symbol(sym.KEY_FLOAT, yytext());
            }
            // fall through
          case 154: break;
          case 69:
            { return symbol(sym.KEY_SHORT, yytext());
            }
            // fall through
          case 155: break;
          case 70:
            { return symbol(sym.KEY_UNION, yytext());
            }
            // fall through
          case 156: break;
          case 71:
            { return symbol(sym.KEY_WHILE, yytext());
            }
            // fall through
          case 157: break;
          case 72:
            { return symbol(sym.KEY_WRITE, yytext());
            }
            // fall through
          case 158: break;
          case 73:
            { return symbol(sym.KEY_DOUBLE, yytext());
            }
            // fall through
          case 159: break;
          case 74:
            { return symbol(sym.KEY_EXT, yytext());
            }
            // fall through
          case 160: break;
          case 75:
            { return symbol(sym.KEY_RET, yytext());
            }
            // fall through
          case 161: break;
          case 76:
            { return symbol(sym.KEY_SIG, yytext());
            }
            // fall through
          case 162: break;
          case 77:
            { return symbol(sym.KEY_SIZEOF, yytext());
            }
            // fall through
          case 163: break;
          case 78:
            { return symbol(sym.KEY_STATIC, yytext());
            }
            // fall through
          case 164: break;
          case 79:
            { return symbol(sym.KEY_STRUCT, yytext());
            }
            // fall through
          case 165: break;
          case 80:
            { return symbol(sym.KEY_SWITCH, yytext());
            }
            // fall through
          case 166: break;
          case 81:
            { return symbol(sym.KEY_DEF, yytext());
            }
            // fall through
          case 167: break;
          case 82:
            { return symbol(sym.KEY_TYPEDEF, yytext());
            }
            // fall through
          case 168: break;
          case 83:
            { return symbol(sym.KEY_CONT, yytext());
            }
            // fall through
          case 169: break;
          case 84:
            { return symbol(sym.KEY_REG, yytext());
            }
            // fall through
          case 170: break;
          case 85:
            { return symbol(sym.KEY_UNSIG, yytext());
            }
            // fall through
          case 171: break;
          case 86:
            { return symbol(sym.KEY_VOL, yytext());
            }
            // fall through
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
