
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package model.compiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KEY_CHAR = 4;
  public static final int OP_ADD_ASS = 36;
  public static final int CHAR = 23;
  public static final int OP_GREATER = 42;
  public static final int KEY_CASE = 3;
  public static final int OP_PAR_OPEN = 34;
  public static final int OP_NOT = 48;
  public static final int OP_AND = 47;
  public static final int KEY_BREAK = 2;
  public static final int INT = 22;
  public static final int OP_INC = 26;
  public static final int OP_DIV = 32;
  public static final int OP_BRACE_OPEN = 24;
  public static final int KEY_DEF = 7;
  public static final int OP_GRE_EQ = 41;
  public static final int KEY_DO = 8;
  public static final int KEY_WHILE = 18;
  public static final int OP_ADD = 29;
  public static final int OP_SUB_ASS = 37;
  public static final int ID = 21;
  public static final int OP_MOD = 33;
  public static final int EOF = 0;
  public static final int OP_PAR_CLOSE = 35;
  public static final int KEY_RET = 14;
  public static final int error = 1;
  public static final int OP_MULT = 31;
  public static final int OP_OR = 46;
  public static final int OP_MULT_ASS = 38;
  public static final int KEY_VOID = 17;
  public static final int OP_ASSIGN = 28;
  public static final int KEY_INT = 12;
  public static final int ERROR = 49;
  public static final int KEY_SHORT = 15;
  public static final int KEY_FOR = 10;
  public static final int KEY_CONST = 5;
  public static final int KEY_ELSE = 9;
  public static final int OP_LESS_EQ = 44;
  public static final int KEY_READ = 19;
  public static final int OP_LESS = 43;
  public static final int OP_DIV_ASS = 39;
  public static final int OP_BRACE_CLOSE = 25;
  public static final int OP_DEC = 27;
  public static final int KEY_IF = 11;
  public static final int KEY_SWITCH = 16;
  public static final int KEY_LONG = 13;
  public static final int OP_SUB = 30;
  public static final int KEY_WRITE = 20;
  public static final int OP_NOT_EQ = 45;
  public static final int OP_EQUAL = 40;
  public static final int KEY_CONT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KEY_BREAK",
  "KEY_CASE",
  "KEY_CHAR",
  "KEY_CONST",
  "KEY_CONT",
  "KEY_DEF",
  "KEY_DO",
  "KEY_ELSE",
  "KEY_FOR",
  "KEY_IF",
  "KEY_INT",
  "KEY_LONG",
  "KEY_RET",
  "KEY_SHORT",
  "KEY_SWITCH",
  "KEY_VOID",
  "KEY_WHILE",
  "KEY_READ",
  "KEY_WRITE",
  "ID",
  "INT",
  "CHAR",
  "OP_BRACE_OPEN",
  "OP_BRACE_CLOSE",
  "OP_INC",
  "OP_DEC",
  "OP_ASSIGN",
  "OP_ADD",
  "OP_SUB",
  "OP_MULT",
  "OP_DIV",
  "OP_MOD",
  "OP_PAR_OPEN",
  "OP_PAR_CLOSE",
  "OP_ADD_ASS",
  "OP_SUB_ASS",
  "OP_MULT_ASS",
  "OP_DIV_ASS",
  "OP_EQUAL",
  "OP_GRE_EQ",
  "OP_GREATER",
  "OP_LESS",
  "OP_LESS_EQ",
  "OP_NOT_EQ",
  "OP_OR",
  "OP_AND",
  "OP_NOT",
  "ERROR"
  };
}

